modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"
issueTrackerURL="https://github.com/RealDarkStudios/PMWeatherAPI/issues" #optional

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
# The JSON Updates will currently fail because the modrinth project does not exist
updateJSONURL="https://api.modrinth.com/updates/pmweatherapi/forge_updates.json" #optional
displayURL="https://github.com/RealDarkStudios/PMWeatherAPI/" #optional
logoFile="logo.png" #optional
credits="All GitHub contributors" #optional
authors = "${mod_authors}" #optional
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies."${mod_id}"]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "${neo_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "pmweather"
type = "required"
versionRange = "${pmweather_version_range}"
ordering = "AFTER"
side = "BOTH"

